import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Events = ({data}) => {
  return(
    <>
      <Head>
        <title>Events App | Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="events-page">
        <h2 className="title">All Events</h2>
        <div className="content">
          {
            data.map(event => (
              <Link href={`/events/${event.id}`} key={event.id} className="card">
                <Image src={event.image} alt={event.title} width={400} height={350} />
                <h2>{event.title}</h2>
              </Link>
            ))
          }
        </div>
      </section>
    </>
  )
};

export default Events;

export async function getStaticProps(context) {
  const {events_categories} = await import("/data/data.json");
  return {
    props: {
      data: events_categories
    }, 
  }
}