import Head from "next/head";

const AboutUs = () => {
  return(
    <>
      <Head>
        <title>Events App | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="about-us">
        <h1 className="about-us-title">ABOUT US PAGE</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae dolorum delectus earum incidunt, porro optio autem doloremque 
          perspiciatis illum aliquam nihil impedit natus ducimus! Tenetur numquam eligendi aspernatur debitis, odit omnis sed deleniti 
          provident porro sequi ratione. Atque rem aspernatur ipsam fugit? Similique, maxime omnis. Harum facilis qui fugit fugiat.
        </p>
        <h2>Lorem ipsum dolor sit amet.</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae dolorum delectus earum incidunt, porro optio autem doloremque 
          perspiciatis illum aliquam nihil impedit natus ducimus! Tenetur numquam eligendi aspernatur debitis, odit omnis sed deleniti 
          provident porro sequi ratione. Atque rem aspernatur ipsam fugit? Similique, maxime omnis. Harum facilis qui fugit fugiat.
        </p>

        <ul className="about-us-list">
          <li>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus praesentium placeat aliquid quae perspiciatis illo hic 
              repudiandae ex earum veritatis, aperiam sunt eligendi minima? Dolorem magnam id eum quo omnis. Velit voluptas veniam, iure magnam 
              laboriosam atque possimus at doloribus id iusto repellat in perspiciatis perferendis optio culpa accusantium consectetur tempore 
              quisquam delectus. Alias voluptatem numquam voluptas soluta. Adipisci quaerat rerum incidunt velit distinctio enim id natus deserunt 
              mollitia odio praesentium nesciunt at quam dignissimos eaque magnam numquam, nemo omnis.
            </p>
          </li>
          <li>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus praesentium placeat aliquid quae perspiciatis illo hic 
              repudiandae ex earum veritatis, aperiam sunt eligendi minima? Dolorem magnam id eum quo omnis. Velit voluptas veniam, iure magnam 
              laboriosam atque possimus at doloribus id iusto repellat in perspiciatis perferendis optio culpa accusantium consectetur tempore 
              quisquam delectus. Alias voluptatem numquam voluptas soluta. Adipisci quaerat rerum incidunt velit distinctio enim id natus deserunt 
              mollitia odio praesentium nesciunt at quam dignissimos eaque magnam numquam, nemo omnis.
            </p>
          </li>
          <li>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus praesentium placeat aliquid quae perspiciatis illo hic 
              repudiandae ex earum veritatis, aperiam sunt eligendi minima? Dolorem magnam id eum quo omnis. Velit voluptas veniam, iure magnam 
              laboriosam atque possimus at doloribus id iusto repellat in perspiciatis perferendis optio culpa accusantium consectetur tempore 
              quisquam delectus. Alias voluptatem numquam voluptas soluta. Adipisci quaerat rerum incidunt velit distinctio enim id natus deserunt 
              mollitia odio praesentium nesciunt at quam dignissimos eaque magnam numquam, nemo omnis.
            </p>
          </li>
        </ul>
      </section>
    </>
  )
};

export default AboutUs;