import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const EventCategoryPage = ({data, pageName}) => {
  return(
    <div className="cat-events">
      <Head>
        <title>Events in {pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className="cat-events-title">Event in {pageName}</h2>
      <div className="cat-events-content">
        {
          data.map(event => (
            <Link href={`/events/${event.city}/${event.id}`} key={event.id} className="card">
              <Image src={event.image} alt={event.title} width={300} height={200} className="card-image"/>
              <h2 className="card-title">{event.title}</h2>
              <p className="card-description">{event.description}</p>
            </Link>
          ))
        } 
      </div>
    </div>
  )
};

export default EventCategoryPage;

export async function getStaticPaths() {
  const {events_categories} = await import("/data/data.json");

  const paths = events_categories.map(event => ({
    params: { 
      cat: event.id
    }
  }))

  return {
    paths,
    fallback: false,
  }
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps(context) {
  const cat = context.params.cat;
  const { allEvents } = await import("/data/data.json");

  const data = allEvents.filter(event => event.city.toLowerCase() === cat);

  return {
    // Passed to the page component as props
    props: { 
      data,
      pageName: cat
    },
  }
}